# stateful set mongodb
### headless service
apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: mongodb
spec:
  ports:
  - protocol: TCP
    port: 27017 # service port
    targetPort: 27017 # container port
  clusterIP: None # headless service
  selector:
    project: roboshop
    component: mongodb
    tier: db
---

## mongodb service
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    component: mongodb
    tier: db
spec:
  ports:
  - protocol: TCP
    port: 27017 # service port
    targetPort: 27017 # container port
  selector:
    project: roboshop
    component: mongodb
    tier: db

## statefulset
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    component: mongodb
    tier: db
spec:
  selector:
    matchLabels:
      project: roboshop
      component: mongodb
      tier: db
  serviceName: "mongodb-headless"
  replicas: 1
  template:
    metadata:
      labels:
        project: roboshop
        component: mongodb
        tier: db
    spec:
      containers:
      - name: mongodb
        image: chandu4234/mongodb:4.0.0
        volumeMounts:
        - name: mongodb
          mountPath: /data/db
  # pvc
  volumeClaimTemplates:
  - metadata:
      name: mongodb
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-ebs"
      resources:
        requests:
          storage: 1Gi